import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { SocialIcon } from 'react-social-icons';
import 'bootstrap/dist/css/bootstrap.min.css';


import React, { useEffect } from 'react';

export default function Home() {
  
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Alejandro Nadal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/stylesheet.css" rel="stylesheet" />
      </Head>

      <section id="intro">   

   	<div className="intro-overlay"></div>	

   	<div className="intro-content">
   		<div className="row">

   			<div className="col-twelve">

	   			<h5>Hello, World.</h5>
	   			<h1>Im Juan Dela Cruz.</h1>

	   			<p className="intro-position">
	   				<span>Front-end Developer</span>
	   				<span>UI/UX Designer</span> 
	   			</p>

	   			<a className="button stroke smoothscroll" href="#about" title="">More About Me</a>

	   		</div>  
   			
   		</div>   		 		
   	</div> 

   	<ul className="intro-social">        
         <li><a href="#"><i className="fa fa-facebook"></i></a></li>
         <li><a href="#"><i className="fa fa-behance"></i></a></li>
         <li><a href="#"><i className="fa fa-twitter"></i></a></li>
         <li><a href="#"><i className="fa fa-dribbble"></i></a></li>
         <li><a href="#"><i className="fa fa-instagram"></i></a></li>
      </ul>    	

   </section> 


   <section id="about">  

   	<div className="row  mx-auto section-intro">
   		<div className="col-twelve ">

   			<h5>About</h5>
   			<h1>Let me introduce myself.</h1>

   			<div className=" row intro-info">
          <div className="col-sm-3 profile_pic">
            <img src="im2.jpg"  alt="Profile Picture"/>
          </div>
   				<div className="col-sm-9">
            <p className="lead ">Software Engineer, focused on Data Engineering and Data Science. Fullbright Grantee, IAESTE intern at Switzerland. I am an Open Source enthusiast, voracious reader,  </p>
          </div>

   				
   			</div>   			

   		</div>   		
   	</div> 

   	<div className="row about-content">

   		<div className="col-six tab-full">

   			<h3>Profile</h3>
   			<p>Lorem ipsum Qui veniam ut consequat ex ullamco nulla in non ut esse in magna sint minim officia consectetur nisi commodo ea magna pariatur nisi cillum.</p>

   			<ul className="info-list">
   				<li>
   					<strong>Fullname:</strong>
   					<span>Juan Dela Cruz</span>
   				</li>
   				<li>
   					<strong>Birth Date:</strong>
   					<span>September 28, 1987</span>
   				</li>
   				<li>
   					<strong>Job:</strong>
   					<span>Freelancer, Frontend Developer</span>
   				</li>
   				<li>
   					<strong>Website:</strong>
   					<span>www.kardswebsite.com</span>
   				</li>
   				<li>
   					<strong>Email:</strong>
   					<span>me@kardswebsite.com</span>
   				</li>

   			</ul> 

   		</div>

   		<div className="col-six tab-full">

   			<h3>Skills</h3>
   			<p>Lorem ipsum Qui veniam ut consequat ex ullamco nulla in non ut esse in magna sint minim officia consectetur nisi commodo ea magna pariatur nisi cillum.</p>

				<ul className="skill-bars">
				   <li>
				   	<div className="progress percent90"><span>90%</span></div>
				   	<strong>HTML5</strong>
				   </li>
				   <li>
				   	<div className="progress percent85"><span>85%</span></div>
				   	<strong>CSS3</strong>
				   </li>
				   <li>
				   	<div className="progress percent70"><span>70%</span></div>
				   	<strong>JQuery</strong>
				   </li>
				   <li>
				   	<div className="progress percent95"><span>95%</span></div>
				   	<strong>PHP</strong>
				   </li>
				   <li>

				   	<div className="progress percent75"><span>75%</span></div>
				   	<strong>Wordpress</strong>
				   </li>
      
				</ul> 

   		</div>

   	</div>

   	<div className="row button-section">
   		<div className="col-twelve">
   			<a href="#contact" title="Hire Me" className="button stroke smoothscroll">Hire Me</a>
   			<a href="#" title="Download CV" className="button button-primary">Download CV</a>
   		</div>   		
   	</div>

   </section>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
